[tool.commitizen]
annotated_tag = true
bump_message = "chore(release): v$new_version [skip-ci]"
changelog_merge_prerelease = true
gpg_sign = true
name = "cz_conventional_commits"
tag_format = "v$version"
update_changelog_on_bump = true
version_scheme = "semver2"
version_provider = "npm"
