[tool.commitizen]
annotated_tag = true
bump_message = "chore(release): v$new_version [skip-ci]"
gpg_sign = true
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver2"
version_provider = "npm"
