name: Create new resume release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Checkout html-resume repo
      uses: actions/checkout@v2
      with:
        repository: arcezd/html-resume
        ref: 'v1.0.3'
        path: html
    - name: Setting compilation vars
      id: vars
      run: echo ::set-output name=sha_short::$(git rev-parse --short HEAD)
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: npm install
    - name: Run task.js for PDF generation [EN]
      id: pdf-generation-en
      run: npm run pdf
      env:
        HTML_TEMPLATE_SUBFOLDER: html/default
        TAG_REF_V: ${{ github.ref }}
        COMMIT_SHA: ${{ steps.vars.outputs.sha_short }}
        GITHUB_REPO: ${{ github.repository }}
    - name: Run task.js for PDF generation [ES]
      id: pdf-generation-es
      run: npm run pdf
      env:
        HTML_TEMPLATE_SUBFOLDER: html/default
        RESUME_LANGUAGE: es
        TAG_REF_V: ${{ github.ref }}
        COMMIT_SHA: ${{ steps.vars.outputs.sha_short }}
        GITHUB_REPO: ${{ github.repository }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Resume JSON to S3 bucket [EN]
      id: upload-release-asset-json-en-to-s3
      uses: arcezd/s3-cp-action@v0.0.1
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DEST_DIR: cv/api/v1/en/resume.json
        SOURCE_DIR: resume_en.json
      with:
        args: --follow-symlinks
    - name: Upload Resume JSON to S3 bucket [ES]
      id: upload-release-asset-json-es-to-s3
      uses: arcezd/s3-cp-action@v0.0.1
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DEST_DIR: cv/api/v1/es/resume.json
        SOURCE_DIR: resume_es.json
      with:
        args: --follow-symlinks
    - name: Upload resume PDF to artifacts [EN]
      id: upload-pdf-artifact-en
      uses: actions/upload-artifact@v1
      with:
        name: diego.arce_resume_en.pdf
        path: diego.arce_resume_en.pdf
    - name: Upload resume PDF to artifacts [ES]
      id: upload-pdf-artifact-es
      uses: actions/upload-artifact@v1
      with:
        name: diego.arce_resume_es.pdf
        path: diego.arce_resume_es.pdf
    - name: Upload Resume PDF to assets [EN]
      id: upload-release-asset-pdf-en
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./diego.arce_resume_en.pdf
        asset_name: diego.arce_resume_en.pdf
        asset_content_type: application/pdf
    - name: Upload Resume PDF to assets [ES]
      id: upload-release-asset-pdf-es
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./diego.arce_resume_es.pdf
        asset_name: diego.arce_resume_es.pdf
        asset_content_type: application/pdf
      
